CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS users (
	id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	name VARCHAR(100),
	email VARCHAR(100) UNIQUE NOT NULL,
	password_hash TEXT NOT NULL,
	is_attendee BOOLEAN DEFAULT FALSE,
	is_organizer BOOLEAN DEFAULT FALSE,
	is_admin BOOLEAN DEFAULT FALSE,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	contact VARCHAR(13)
);

CREATE TABLE IF NOT EXISTS admin_users (
	id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
	name VARCHAR(100) NOT NULL,
	email VARCHAR(100) UNIQUE NOT NULL,
	password_hash TEXT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
